**NumPy** (Numerical Python) — это библиотека для языка программирования Python, предназначенная для работы с многомерными массивами и матрицами, а также для выполнения различных математических и статистических операций над ними. Основная сила NumPy заключается в эффективной обработке больших объемов данных и возможности легко управлять данными с помощью различных функций.

### Основные особенности NumPy:

1. **Многомерные массивы (ndarray)**: 
   - Основная структура данных NumPy — это многомерный массив, называемый `ndarray`. Он позволяет работать с массивами данных произвольной размерности (1D, 2D, 3D и более). 
   - В отличие от стандартных списков Python, массивы NumPy занимают меньше места и обеспечивают более быструю обработку данных.

2. **Высокая производительность**:
   - NumPy написан на C, что делает его выполнение значительно быстрее по сравнению с обычными Python списками.
   - Поддерживает векторизацию операций, что позволяет избежать использования циклов для работы с данными.

3. **Удобные операции с массивами**:
   - Поддерживает широкие возможности для математических операций, таких как сложение, вычитание, умножение, деление массивов, а также линейную алгебру (матрицы, векторы).
   - Функции для работы со статистикой, тригонометрией, логарифмами и др.

4. **Интеграция с другими библиотеками**:
   - NumPy тесно интегрирован с такими библиотеками как **Pandas**, **SciPy**, **Matplotlib**, что делает его основой для научных расчетов, анализа данных и машинного обучения.

5. **Поддержка работы с N-мерными массивами**:
   - Можно работать с данными любой размерности, начиная от одномерных массивов до массивов с несколькими измерениями (например, 3D, 4D и более).

6. **Манипуляции с формами данных**:
   - NumPy поддерживает такие операции, как изменение формы массива, транспонирование, объединение и разделение массивов.

7. **Функции для случайных чисел и статистики**:
   - NumPy предоставляет возможности для генерации случайных чисел, выполнения статистических расчетов, работы с распределениями вероятностей.

### Где используется NumPy:

- **Научные вычисления**: NumPy широко используется в научных проектах, связанных с физикой, химией, биологией и другими областями, где необходима работа с большими массивами данных.
- **Анализ данных**: Основной инструмент для работы с данными в Python, так как его часто используют вместе с Pandas для обработки больших объемов информации.
- **Машинное обучение**: NumPy является основой для многих библиотек машинного обучения, таких как TensorFlow и PyTorch, которые зависят от массивов для выполнения математических операций.
- **Компьютерное зрение и обработка изображений**: Часто используется в библиотеках для обработки изображений (например, OpenCV).


```python
(function) def array(
    object: object,
    dtype: None = ...,
    *,
    copy: bool | _CopyMode | None = ...,
    order: _OrderKACF = ...,
    subok: bool = ...,
    ndmin: int = ...,
    like: _SupportsArrayFunc | None = ...
) -> NDArray[Any]
```

In [ ]:
import numpy as np 

### Массив объязательно должен иметь один тип данных
- int - `[1, 2, 3, 4, 5]`
- str - `['1', '2', '3', '4', '5']`
- и т.д.

In [13]:
array_a = np.array([1, 2, 3, 4, 5])
array_a.dtype

dtype('int64')

In [14]:
array_b = np.array(['1', 1, True, 2, 5])
array_b.dtype

dtype('<U21')

In [16]:
array_a_python = [1,2,3,4,5,6]

# Получения массива элементов по индексу на пайтоне 
# без использования циклов или же функций numpy не получиться
array_a_python[[1,1,1,2,3]]

TypeError: list indices must be integers or slices, not list

In [19]:
# Индексирования numpy получется более гипкое чем у обычных списков пайтон. можно указывать несколько индексов в одной команде
array_a[[1, 2, 3, 1, 1, 1, 1]] # Получения массива элементов по индексу

array([2, 3, 4, 2, 2, 2, 2])

In [23]:
# Это способ выбора элементов массива с использованием списка или массива булевых значений (`True` или `False`).
array_c = np.array([1, 2, 3, 4, 5])
array_c[[True, False, True, False, True]] # Получения массива элементов по индексу

array([1, 3, 5])

### Описание действия:

Массив `array_c` — это одномерный массив `[1, 2, 3, 4, 5]`. 
Булевый массив `[True, False, True, False, True]` указывает, какие элементы нужно выбрать:

- Если значение `True`, элемент будет взят.
- Если `False`, элемент будет пропущен.

Результат: `[1, 3, 5]` — элементы массива, соответствующие позициям с `True`.

`````

In [29]:
array_d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# В данном примере используется метод reshape для изменения формы массива.
array_e = array_d.reshape(3, 3)
array_e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Описание действия:

- `array_d` — одномерный массив `[1, 2, 3, 4, 5, 6, 7, 8, 9]`.
- Метод `reshape(3, 3)` преобразует одномерный массив в двумерный массив 3x3, где:
  - Первое число указывает на количество строк.
  - Второе — на количество столбцов.

Результат: массив
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

In [40]:
# В данном примере выполняется обращение к элементу двумерного массива `array_e`, 
# но используются два разных синтаксиса.
print('Обычное обращение по индексам в два этапа:', array_e[2][1])
print('Обращение по индексам в два этапа numpy:', array_e[2, 1])

Обычное обращение по индексам в два этапа: 8
Обращение по индексам в два этапа numpy: 8


`````

# Типы NumPy

```python
{'bool': numpy.bool,
 'float16': numpy.float16,
 'float32': numpy.float32,
 'float64': numpy.float64,
 'longdouble': numpy.longdouble,
 'complex64': numpy.complex64,
 'complex128': numpy.complex128,
 'clongdouble': numpy.clongdouble,
 'bytes_': numpy.bytes_,
 'str_': numpy.str_,
 'void': numpy.void,
 'object_': numpy.object_,
 'datetime64': numpy.datetime64,
 'timedelta64': numpy.timedelta64,
 'int8': numpy.int8,
 'byte': numpy.int8,
 'uint8': numpy.uint8,
 'ubyte': numpy.uint8,
 'int16': numpy.int16,
 'short': numpy.int16,
 'uint16': numpy.uint16,
 'ushort': numpy.uint16,
 'intc': numpy.intc,
 'uintc': numpy.uintc,
 'int32': numpy.int32,
...
 'bytes': numpy.bytes_,
 'a': numpy.bytes_,
 'int': numpy.int64,
 'str': numpy.str_,
 'unicode': numpy.str_}
```

### Числовые типы:
1. **`numpy.bool`** — Булевый тип, представляющий значения `True` и `False`.
2. **`numpy.float16`** — Число с плавающей запятой (полуточная точность) на 16 бит.
3. **`numpy.float32`** — Число с плавающей запятой одинарной точности (32 бита).
4. **`numpy.float64`** — Число с плавающей запятой двойной точности (64 бита).
5. **`numpy.longdouble`** — Число с плавающей запятой расширенной точности (может быть более 64 бит, зависит от архитектуры).
6. **`numpy.complex64`** — Комплексное число, в котором действительная и мнимая части представлены числами с плавающей запятой одинарной точности (по 32 бита).
7. **`numpy.complex128`** — Комплексное число с действительной и мнимой частями двойной точности (по 64 бита).
8. **`numpy.clongdouble`** — Комплексное число с действительными и мнимыми частями расширенной точности.
9. **`numpy.int8`** — Целое число со знаком на 8 бит (от -128 до 127).
10. **`numpy.uint8`** — Беззнаковое целое число на 8 бит (от 0 до 255).
11. **`numpy.int16`** — Целое число со знаком на 16 бит (от -32768 до 32767).
12. **`numpy.uint16`** — Беззнаковое целое число на 16 бит (от 0 до 65535).
13. **`numpy.int32`** — Целое число со знаком на 32 бита.
14. **`numpy.uint32`** — Беззнаковое целое число на 32 бита.
15. **`numpy.int64`** — Целое число со знаком на 64 бита.
16. **`numpy.uint64`** — Беззнаковое целое число на 64 бита.
17. **`numpy.intc`** — Целое число, аналогичное типу `int` в языке C (обычно 32 или 64 бита, зависит от платформы).
18. **`numpy.uintc`** — Беззнаковое целое число аналогичное `unsigned int` в языке C.

### Комплексные типы:
19. **`numpy.bytes_`** — Представляет строки байтов (аналог `bytes` в Python).
20. **`numpy.str_`** — Строка символов Unicode фиксированной длины (аналог `str` в Python).

### Специальные типы:
21. **`numpy.void`** — Используется для произвольных данных, таких как структуры и записи.
22. **`numpy.object_`** — Общий тип для любых объектов Python (например, списков, кортежей).
23. **`numpy.datetime64`** — Дата и время с точностью до наносекунд.
24. **`numpy.timedelta64`** — Представляет разницу во времени.

### Псевдонимы:
25. **`numpy.byte`** — Псевдоним для `numpy.int8`.
26. **`numpy.ubyte`** — Псевдоним для `numpy.uint8`.
27. **`numpy.short`** — Псевдоним для `numpy.int16`.
28. **`numpy.ushort`** — Псевдоним для `numpy.uint16`.
29. **`numpy.int`** — Псевдоним для `numpy.int64`.
30. **`numpy.unicode`** — Псевдоним для `numpy.str_`.

### Примечание:
Типы, такие как `intc`, `uintc`, `intp` и другие, зависят от архитектуры системы и могут варьироваться (например, на 32-битных системах они могут иметь меньший размер).


#### Что бы посмотреть все типа данных NumPy
```python
import numpy as np
np.sctypeDict
np.sctypeDict
```

<i> 1000 элементов x int8 = 1000 байт.
1000 элементов x int64 = 8000 байт.<i>

In [ ]:
import numpy as np

In [55]:
array_float = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
# array_float = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
# array_float = np.array([[1, 2, 3], [4, 5, 6]], dtype='float')
# array_float = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
# array_float = np.array([[1, 2, 3], [4, 5, 6]], dtype='float32')
# array_float = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float16)
# array_float = np.array([[1, 2, 3], [4, 5, 6]], dtype='float16')
array_float.dtype

dtype('float64')

In [59]:
# Это базовый тип Python.
str(10)

# Тип строки в контексте массивов NumPy, 
# который используется для совместимости внутри библиотек NumPy.
np.str_(10)

np.float32(10)
np.float64(10)

np.float64(10.0)